# values.yaml
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  useTestSchema: true
  auth_enabled: false
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
gateway:
  enabled: false
memcachedChunks:
  enabled: false
memcachedResults:
  enabled: false
canary:
  enabled: false
