apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-test-app
  namespace: observability
  labels:
    app: tempo-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo-test-app
  template:
    metadata:
      labels:
        app: tempo-test-app
    spec:
      containers:
      - name: tempo-test-app
        image: tempo-test-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: tempo-test-app
  namespace: observability
spec:
  selector:
    app: tempo-test-app
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP 